// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdlWU39mV4KuMq1BaKWqZOqDIyksnDPqo',
    appId: '1:972670513006:web:d5938aec2586dccdfb1b7f',
    messagingSenderId: '972670513006',
    projectId: 'post-stroke-speech-thera-ef735',
    authDomain: 'post-stroke-speech-thera-ef735.firebaseapp.com',
    storageBucket: 'post-stroke-speech-thera-ef735.firebasestorage.app',
    measurementId: 'G-WSD5NYLMP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvFEyjxmT9eAglly2BGJ1k8sEJs7wv9fk',
    appId: '1:972670513006:android:845a88fb0b5dae19fb1b7f',
    messagingSenderId: '972670513006',
    projectId: 'post-stroke-speech-thera-ef735',
    storageBucket: 'post-stroke-speech-thera-ef735.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC0I3Wd4lczUlNG713bF7FXaVue2otlWY',
    appId: '1:972670513006:ios:d255b66f643ac700fb1b7f',
    messagingSenderId: '972670513006',
    projectId: 'post-stroke-speech-thera-ef735',
    storageBucket: 'post-stroke-speech-thera-ef735.firebasestorage.app',
    androidClientId: '972670513006-nscr6ms7ubjb8rbfsf4l3pev2od4knum.apps.googleusercontent.com',
    iosClientId: '972670513006-upfor3lt27th54ircs8k151oka6u5829.apps.googleusercontent.com',
    iosBundleId: 'com.example.speechTherapy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC0I3Wd4lczUlNG713bF7FXaVue2otlWY',
    appId: '1:972670513006:ios:d255b66f643ac700fb1b7f',
    messagingSenderId: '972670513006',
    projectId: 'post-stroke-speech-thera-ef735',
    storageBucket: 'post-stroke-speech-thera-ef735.firebasestorage.app',
    androidClientId: '972670513006-nscr6ms7ubjb8rbfsf4l3pev2od4knum.apps.googleusercontent.com',
    iosClientId: '972670513006-upfor3lt27th54ircs8k151oka6u5829.apps.googleusercontent.com',
    iosBundleId: 'com.example.speechTherapy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdlWU39mV4KuMq1BaKWqZOqDIyksnDPqo',
    appId: '1:972670513006:web:308760e90d0f617efb1b7f',
    messagingSenderId: '972670513006',
    projectId: 'post-stroke-speech-thera-ef735',
    authDomain: 'post-stroke-speech-thera-ef735.firebaseapp.com',
    storageBucket: 'post-stroke-speech-thera-ef735.firebasestorage.app',
    measurementId: 'G-38SRJD8MTL',
  );
}
